name: fcm-topic-all-test

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/3 * * * *" # каждые 3 минуты

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install firebase-admin

      - name: Send silent push to topic "all"
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
        run: |
          node <<'NODE'
          const admin = require("firebase-admin");

          // Инициализация Admin SDK из секрета
          admin.initializeApp({
            credential: admin.credential.cert(
              JSON.parse(process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON)
            )
          });

          // Отправка сообщения в топик "all"
          admin.messaging().send({
            topic: "all",
            apns: {
              headers: {
                "apns-push-type": "background",
                "apns-priority": "5"
              },
              payload: { aps: { "content-available": 1 } }
            },
            data: { type: "widget_weather_refresh" }
          })
          .then((response) => {
            console.log("✅ Push sent:", response);
          })
          .catch((error) => {
            console.error("❌ Error sending push:", error);
            process.exit(1);
          });
          NODE
